FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["Birt.App/Birt.App.csproj", "Birt.App/"]
RUN dotnet restore "Birt.App/Birt.App.csproj"
COPY . .
RUN dotnet publish "Birt.App/Birt.App.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 80
ENTRYPOINT ["dotnet", "Birt.App.dll"]
