FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["RdfService/RdfService.csproj", "RdfService/"]
RUN dotnet restore "RdfService/RdfService.csproj"
COPY . .
RUN dotnet publish "RdfService/RdfService.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish .
COPY RdfService/properties_ontology.ttl .
EXPOSE 80
ENTRYPOINT ["dotnet", "RdfService.dll"]
